<a href="https://colab.research.google.com/github/rodolfoharley/7_Days_of_Code_Alura-Python-Pandas_Rodolfo/blob/main/Aula_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd

# URL da API do GitHub para listar o conteúdo do diretório
api_url = 'https://api.github.com/repos/rodolfoharley/7_Days_of_Code_Alura-Python-Pandas/contents/Dia_1-Importando_dados/Datasets/dados_emprestimos'

response = requests.get(api_url)
files = response.json()

# Filtrar apenas os arquivos CSV
csv_files = [file['download_url'] for file in files if file['name'].endswith('.csv')]

# Lista para armazenar os dataframes
dfs = []

for file_url in csv_files:
    df = pd.read_csv(file_url)
    dfs.append(df)

# Concatenar todos os dataframes
emprestimos = pd.concat(dfs, ignore_index=True)

# Exibir o dataframe final
emprestimos.tail()

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

In [ ]:
emprestimos.value_counts()

id_emprestimo  codigo_barras  data_renovacao                 data_emprestimo                data_devolucao                 matricula_ou_siape  tipo_vinculo_usuario
709704         2006021442     2010/01/17 18:56:43.923000000  2010/01/04 09:58:46.522000000  2010/02/01 13:59:02.528000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709705         2009032168     2010/01/17 18:56:43.909000000  2010/01/04 09:58:46.549000000  2010/01/20 13:14:34.464000000  2.008010e+09        ALUNO DE GRADUAÇÃO        7
709698         2009047725     2010/01/18 14:44:41.163000000  2010/01/04 09:21:19.099000000  2010/02/02 12:02:38.444000000  2.009047e+09        ALUNO DE GRADUAÇÃO        3
709686         2006017618     2010/01/26 08:07:01.738000000  2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000  2.008112e+09        ALUNO DE PÓS-GRADUAÇÃO    2
2461099        2012008348     2016/06/27 20:35:46.855000000  2016/06/14 11:20:33.254000000  2016/07/11 14:37:29.000000000  2.015022e+09        ALUNO DE GRADUAÇÃO        2
                                                                                                                                                                        ..
1443389        2011018954     2013/03/22 13:18:55.037000000  2013/03/07 11:21:26.480000000  2013/04/08 20:26:07.000000000  2.010046e+09        ALUNO DE GRADUAÇÃO        1
1443390        2009056314     2013/03/21 09:28:45.689000000  2013/03/07 11:21:28.899000000  2013/04/05 18:18:00.000000000  2.011015e+09        ALUNO DE GRADUAÇÃO        1
1443393        2012037906     2013/03/20 20:17:10.574000000  2013/03/07 11:24:19.326000000  2013/03/25 08:58:44.000000000  2.011038e+09        ALUNO DE GRADUAÇÃO        1
1443395        2011033069     2013/04/07 01:06:51.679000000  2013/03/07 11:25:22.661000000  2013/05/07 16:19:34.000000000  2.011106e+09        ALUNO DE PÓS-GRADUAÇÃO    1
10322328       2014070441     2018/01/15 12:26:00.697000000  2017/12/29 18:21:09.060000000  2018/01/31 18:50:25.000000000  2.014063e+09        ALUNO DE GRADUAÇÃO        1
Name: count, Length: 968028, dtype: int64

In [ ]:
emprestimos = emprestimos.drop_duplicates()

In [ ]:
import requests
import pandas as pd

# URL do arquivo .parquet no GitHub
url = 'https://github.com/rodolfoharley/7_Days_of_Code_Alura-Python-Pandas/raw/main/Dia_1-Importando_dados/Datasets/dados_exemplares.parquet'

# Fazer o download do arquivo
response = requests.get(url)
with open('temp.parquet', 'wb') as f:
    f.write(response.content)

# Ler o arquivo .parquet baixado
acervo = pd.read_parquet('temp.parquet', engine='pyarrow')

# Exibir as primeiras linhas do dataframe
acervo.head()

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema
index,,,,,,,
0,5,L000003,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,694,1
1,4,L000002,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,688,1
2,3,L000001,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,638,1
3,7,L000114,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,5
5,10,L000041,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,657,15

In [ ]:
acervo.value_counts()

id_exemplar  codigo_barras  colecao            biblioteca                                             status_material  localizacao  registro_sistema
3            L000001        Acervo Circulante  Biblioteca Central Zila Mamede                         ESPECIAL         638          1                   1
1070480      2013071582     Acervo Circulante  Biblioteca Setorial do Centro Ciências da Saúde - CCS  REGULAR          340          200283              1
1070506      2013077711     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          354          200288              1
1070505      2013077710     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          327          200288              1
1070504      2013077807     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          348          200286              1
                                                                                                                                                       ..
232120       2007034699     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          652          96457               1
232119       2007034703     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          628          96456               1
232118       2007036783     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          618          96301               1
232117       2007040275     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          680          96301               1
1353476      2019012276     Acervo Circulante  Biblioteca Central Zila Mamede                         ESPECIAL         962          268236              1
Name: count, Length: 546237, dtype: int64

In [ ]:
emprestimos_X_acervo = pd.merge(emprestimos, acervo, on='codigo_barras', how='inner')
emprestimos_X_acervo.dropna()